### ISSUE TITLE
Question about executing faster-lio with LIO-SAM dataset

### ISSUE THREAD

**Issue by Taeyoung96** [gaoxiang12/faster-lio#28]
@gaoxiang12  
Hi, Thanks for your great work!  
I have 2 questions about faster-lio executing with Velodyne VLP 16.  
1. In [paper](https://ieeexplore.ieee.org/abstract/document/9718203), there is an experiment with LIO-SAM dataset.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/172592264-b564f4d0-1dd1-457e-9625-39ca8f38da7f.png" width = "700" ></p>  

  On the LIO-SAM repository, some [sample datasets](https://github.com/TixiaoShan/LIO-SAM#sample-datasets) are provided.  
  Then, which sequence did you use to write a paper?  
    Do you make ground-truth trajectories with `gps/fix` topic in the sample dataset?  

2. I want to test Faster-lio algorithm with aggressive motion using Velodyne LiDAR.  
I find the simple dataset provided in [Rotation dataset in LIO-SAM](https://github.com/TixiaoShan/LIO-SAM#sample-datasets).  
But I got a wired result with provided `velodyne_liosam.yaml`.  
Actually, I fixed some parameters like below.  
```
common:
    dataset: "liosam"
    lid_topic:  "points_raw"
    imu_topic:  "imu_correct"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    blind: 4
    time_scale: 1e3             # Compatible with time units of different datasets

mapping:
    acc_cov: 3.9939570888238808e-03
    gyr_cov: 1.5636343949698187e-03
    b_acc_cov: 6.4356659353532566e-05
    b_gyr_cov: 3.5640318696367613e-05
    fov_degree: 180
    det_range: 100.0
    extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0, 0, 0]
    extrinsic_R: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]

publish:
    path_publish_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    scan_effect_pub_en: true    # true: publish the pointscloud of effect point
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

path_save_en: true                 # Save trajectories for accuracy calculations and comparisons

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

feature_extract_enable: false
point_filter_num: 3
max_iteration: 3
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 1000

ivox_grid_resolution: 1.0        # default=0.2
ivox_nearby_type: 26             # 6, 18, 26
esti_plane_threshold: 0.1        # default=0.1
```

I shared my result video.  
- Rotation dataset with LIO-SAM - [[Link](https://drive.google.com/file/d/1uun8IEUcBILP50sy99MF3z9EftqjrEse/view?usp=sharing)].  
- Rotation dataset with Faster-LIO - [[Link](https://drive.google.com/file/d/1yR2Z9xQLKWnD3vZ0m4HpP_lAfluIrEDP/view?usp=sharing)].  

Do I need to fix other parameters?  
Does it right that the faster-lio algorithm doesn't work well in this rotation dataset?  
(I guess correspondence issue or measurement model or direct method or what else...  :monocle_face:)  

I'll look forward to your reply.  
Thanks,
